package com.sd.vo;

// Generated 2015-5-18 9:04:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name="tarea")
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(true)
public class Area implements java.io.Serializable {
	@Column(name="ta_id")
	private Integer taId;
	@Id
	@Column(name="ta_code")
	private String taCode;
	
	@Column(name="ta_name")
	private String taName;
	@Column(name="ta_level")
	private Integer taLevel;
	@Column(name="updatetime")
	private Date updatetime;
	@Column(name="createtime")
	private Date createtime;
	@Column(name="status")
	private Integer status;

	public Area() {
	}

	public Area(String taCode, String taName, Integer taLevel,
			Date updatetime, Date createtime, Integer status) {
		this.taCode = taCode;
		this.taName = taName;
		this.taLevel = taLevel;
		this.updatetime = updatetime;
		this.createtime = createtime;
		this.status = status;
	}

	public Integer getTaId() {
		return this.taId;
	}

	public void setTaId(Integer taId) {
		this.taId = taId;
	}

	public String getTaCode() {
		return this.taCode;
	}

	public void setTaCode(String taCode) {
		this.taCode = taCode;
	}

	public String getTaName() {
		return this.taName;
	}

	public void setTaName(String taName) {
		this.taName = taName;
	}

	public Integer getTaLevel() {
		return this.taLevel;
	}

	public void setTaLevel(Integer taLevel) {
		this.taLevel = taLevel;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
