package com.sd.vo;

// Generated 2015-5-18 9:04:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * Tfeedback generated by hbm2java
 */
@Entity
@Table(name="tfeedback")
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(true)
public class Feedback extends BaseVo  {
	public String getTelePhone() {
		return telePhone;
	}

	public void setTelePhone(String telePhone) {
		this.telePhone = telePhone;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="fb_id")
	private Integer fbId;
	
	@Column(name="fb_uid")
	private String fbUid;
	
	@Column(name="title")
	private String title;
	
	@Column()
	private String telePhone;
	
	@Column(name="fb_detail")
	private String fbDetail;
	@Column()
	private String phoneInfo;
	
	
	public String getPhoneInfo() {
		return phoneInfo;
	}

	public void setPhoneInfo(String phoneInfo) {
		this.phoneInfo = phoneInfo;
	}

	@Column(name="fb_datetime")
	private Date fbDatetime;
	
	@Column(name="fb_pic")
	private String fbPic;
	
	@Column(name="fb_reply")
	private String fbReply;
	
	@Column(name="fb_reply_time")
	private Date fbReplyTime;
	
	@Column(name="fb_status")
	private Integer fbStatus;
	
	@Column(name="fb_CreateTime")
	private Date fbCreateTime;
	
	@Column(name="fb_updatetime")
	private Date fbUpdatetime;
	
	@Column(name="fb_isdel")
	private Integer fbIsdel;

	public Feedback() {
	}

	public Feedback(String fbUid, String fbDetail, Date fbDatetime,
			String fbPic, String fbReply, Date fbReplyTime, Integer fbStatus,
			Date fbCreateTime, Date fbUpdatetime, Integer fbIsdel) {
		this.fbUid = fbUid;
		this.fbDetail = fbDetail;
		this.fbDatetime = fbDatetime;
		this.fbPic = fbPic;
		this.fbReply = fbReply;
		this.fbReplyTime = fbReplyTime;
		this.fbStatus = fbStatus;
		this.fbCreateTime = fbCreateTime;
		this.fbUpdatetime = fbUpdatetime;
		this.fbIsdel = fbIsdel;
	}

	public Integer getFbId() {
		return this.fbId;
	}

	public void setFbId(Integer fbId) {
		this.fbId = fbId;
	}


	public String getFbUid() {
		return fbUid;
	}

	public void setFbUid(String fbUid) {
		this.fbUid = fbUid;
	}

	public String getFbDetail() {
		return this.fbDetail;
	}

	public void setFbDetail(String fbDetail) {
		this.fbDetail = fbDetail;
	}

	public Date getFbDatetime() {
		return this.fbDatetime;
	}

	public void setFbDatetime(Date fbDatetime) {
		this.fbDatetime = fbDatetime;
	}

	public String getFbPic() {
		return this.fbPic;
	}

	public void setFbPic(String fbPic) {
		this.fbPic = fbPic;
	}

	public String getFbReply() {
		return this.fbReply;
	}

	public void setFbReply(String fbReply) {
		this.fbReply = fbReply;
	}

	public Date getFbReplyTime() {
		return this.fbReplyTime;
	}

	public void setFbReplyTime(Date fbReplyTime) {
		this.fbReplyTime = fbReplyTime;
	}

	public Integer getFbStatus() {
		return this.fbStatus;
	}

	public void setFbStatus(Integer fbStatus) {
		this.fbStatus = fbStatus;
	}

	public Date getFbCreateTime() {
		return this.fbCreateTime;
	}

	public void setFbCreateTime(Date fbCreateTime) {
		this.fbCreateTime = fbCreateTime;
	}

	public Date getFbUpdatetime() {
		return this.fbUpdatetime;
	}

	public void setFbUpdatetime(Date fbUpdatetime) {
		this.fbUpdatetime = fbUpdatetime;
	}

	public Integer getFbIsdel() {
		return this.fbIsdel;
	}

	public void setFbIsdel(Integer fbIsdel) {
		this.fbIsdel = fbIsdel;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
