package com.sd.vo;

// Generated 2015-5-18 9:04:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;

/**
 * Thospitalbase generated by hbm2java
 */
@Entity
@Table(name="thospital")
@DynamicInsert(true)
@DynamicUpdate(true)
@SelectBeforeUpdate(true)
public class Thospital implements java.io.Serializable {
	@Column(name="hos_id")
	private Integer hosId;
	@Id
	@Column(name="hos_code")
	private String hosCode;
	@Column(name="hos_name")
	private String hosName;
	@Column(name="hos_local")
	private String hosLocal;
	
	@Column(name="hos_localName")
	private String localName;
	
	@Column(name="hos_desc")
	private String hosDesc;
	@Column(name="updatetime")
	private Date updatetime;
	@Column(name="createtime")
	private Date createtime;
	@Column(name="status")
	private Integer status;

	public Thospital() {
	}

	public Thospital(String hosCode, String hosName, String hosLocal,
			String hosDesc, Date updatetime, Date createtime, Integer status) {
		this.hosCode = hosCode;
		this.hosName = hosName;
		this.hosLocal = hosLocal;
		this.hosDesc = hosDesc;
		this.updatetime = updatetime;
		this.createtime = createtime;
		this.status = status;
	}

	public Integer getHosId() {
		return this.hosId;
	}

	public void setHosId(Integer hosId) {
		this.hosId = hosId;
	}

	public String getHosCode() {
		return this.hosCode;
	}

	public void setHosCode(String hosCode) {
		this.hosCode = hosCode;
	}

	public String getHosName() {
		return this.hosName;
	}

	public void setHosName(String hosName) {
		this.hosName = hosName;
	}

	public String getHosLocal() {
		return this.hosLocal;
	}

	public void setHosLocal(String hosLocal) {
		this.hosLocal = hosLocal;
	}

	public String getHosDesc() {
		return this.hosDesc;
	}

	public void setHosDesc(String hosDesc) {
		this.hosDesc = hosDesc;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getLocalName() {
		return localName;
	}

	public void setLocalName(String localName) {
		this.localName = localName;
	}

}
