package com.sd.vo;

// Generated 2015-5-18 9:04:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Trespic generated by hbm2java
 */
public class Trespic implements java.io.Serializable {

	private Integer rpId;
	private String rpUrl;
	private Integer rpUploaderid;
	private Date rpDate;
	private String rpIp;
	private String rpQuoteGid;
	private Integer rpWidth;
	private Integer rpHeight;
	private BigDecimal rpAngle;
	private String rpRz1;
	private String rpRz2;
	private String rpRz3;
	private Date rpUpdatetime;
	private Integer rpIsdel;

	public Trespic() {
	}

	public Trespic(String rpQuoteGid) {
		this.rpQuoteGid = rpQuoteGid;
	}

	public Trespic(String rpUrl, Integer rpUploaderid, Date rpDate,
			String rpIp, String rpQuoteGid, Integer rpWidth, Integer rpHeight,
			BigDecimal rpAngle, String rpRz1, String rpRz2, String rpRz3,
			Date rpUpdatetime, Integer rpIsdel) {
		this.rpUrl = rpUrl;
		this.rpUploaderid = rpUploaderid;
		this.rpDate = rpDate;
		this.rpIp = rpIp;
		this.rpQuoteGid = rpQuoteGid;
		this.rpWidth = rpWidth;
		this.rpHeight = rpHeight;
		this.rpAngle = rpAngle;
		this.rpRz1 = rpRz1;
		this.rpRz2 = rpRz2;
		this.rpRz3 = rpRz3;
		this.rpUpdatetime = rpUpdatetime;
		this.rpIsdel = rpIsdel;
	}

	public Integer getRpId() {
		return this.rpId;
	}

	public void setRpId(Integer rpId) {
		this.rpId = rpId;
	}

	public String getRpUrl() {
		return this.rpUrl;
	}

	public void setRpUrl(String rpUrl) {
		this.rpUrl = rpUrl;
	}

	public Integer getRpUploaderid() {
		return this.rpUploaderid;
	}

	public void setRpUploaderid(Integer rpUploaderid) {
		this.rpUploaderid = rpUploaderid;
	}

	public Date getRpDate() {
		return this.rpDate;
	}

	public void setRpDate(Date rpDate) {
		this.rpDate = rpDate;
	}

	public String getRpIp() {
		return this.rpIp;
	}

	public void setRpIp(String rpIp) {
		this.rpIp = rpIp;
	}

	public String getRpQuoteGid() {
		return this.rpQuoteGid;
	}

	public void setRpQuoteGid(String rpQuoteGid) {
		this.rpQuoteGid = rpQuoteGid;
	}

	public Integer getRpWidth() {
		return this.rpWidth;
	}

	public void setRpWidth(Integer rpWidth) {
		this.rpWidth = rpWidth;
	}

	public Integer getRpHeight() {
		return this.rpHeight;
	}

	public void setRpHeight(Integer rpHeight) {
		this.rpHeight = rpHeight;
	}

	public BigDecimal getRpAngle() {
		return this.rpAngle;
	}

	public void setRpAngle(BigDecimal rpAngle) {
		this.rpAngle = rpAngle;
	}

	public String getRpRz1() {
		return this.rpRz1;
	}

	public void setRpRz1(String rpRz1) {
		this.rpRz1 = rpRz1;
	}

	public String getRpRz2() {
		return this.rpRz2;
	}

	public void setRpRz2(String rpRz2) {
		this.rpRz2 = rpRz2;
	}

	public String getRpRz3() {
		return this.rpRz3;
	}

	public void setRpRz3(String rpRz3) {
		this.rpRz3 = rpRz3;
	}

	public Date getRpUpdatetime() {
		return this.rpUpdatetime;
	}

	public void setRpUpdatetime(Date rpUpdatetime) {
		this.rpUpdatetime = rpUpdatetime;
	}

	public Integer getRpIsdel() {
		return this.rpIsdel;
	}

	public void setRpIsdel(Integer rpIsdel) {
		this.rpIsdel = rpIsdel;
	}

}
